---
title: "DataAnalysis"
author: "Tariqul Islam"
date: "8/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Analysis Steps

```{r cars}
library(dplyr)
```

```{r}

## Read the Feature COlumn names from "fetures.txt"
colNames <- read.table("UCI HAR Dataset/features.txt")
colNames <- colNames[,2]

## Read Training set features and labels

X_trainData <- read.table("UCI HAR Dataset/train/X_train.txt", col.names = colNames)
Y_trainData <- read.table("UCI HAR Dataset/train/Y_train.txt", col.names = c("ActivityLabel"))

## Merge the two tables into one
trainset <- cbind(Y_trainData, X_trainData)


## Read Test set features and labels

X_testData <- read.table("UCI HAR Dataset/test/X_test.txt", col.names = colNames)
Y_testData <- read.table("UCI HAR Dataset/test/Y_test.txt", col.names = c("ActivityLabel"))

## Merge the two tables into one
testset <- cbind(Y_testData, X_testData)


## Combine the Train set and Test set data to form a single dataframe

dataset <- rbind(trainset, testset)

## Remove temporary DataFrames from the Memory

rm(X_trainData, Y_trainData, trainset, X_testData, Y_testData, testset)

```


```{r}
## Extract only the Means and Standard Deviations of the measurements
cols <- grep("(mean|std)[...]", names(dataset), value = TRUE)
dataset <- select(dataset, c(ActivityLabel, cols))

## Clean Column names
names(dataset) <- gsub("[.]{1,3}", "_", names(dataset))
```

```{r}
# Read Activity labels from "activity_labels.txt" as a table
activities <- read.table("UCI HAR Dataset/activity_labels.txt", col.names = c("ActivityLabel", "ActivityName"))

# Remove "_" from activity names
activities <- activities %>%
  mutate(ActivityName = sub("_", " ", ActivityName))


# Merge the Activity Table with the dataset matching by the ActivityLabel
dataset <- merge(activities, dataset, by = "ActivityLabel")


# Remove ActivityLabel Column from the dataset
dataset <- dataset %>%
  select(-"ActivityLabel")
```


```{r}
head(dataset)
```

